#include <string.h>

#define INCL_WIN
#define INCL_DOS
#define INCL_WPERRORS
#include <os2.h>

/*
 * This file was generated by the SOM Compiler.
 * FileName: qdesk.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define GEQueryDesktop_Class_Source
#include "qdesk.ih"

#include <wpfolder.h>

#include "qdparm.h"

SOM_Scope BOOL   SOMLINK qt_wpSetup(GEQueryDesktop *somSelf,
                                    PSZ pszSetupString)
{
         CHAR       szValue[CCHMAXPATH];
         ULONG      cbBuffer;
         ULONG      cb;
         PSZ        pszRealName;
         CHAR       ObjectID[50];
         BOOL       Error = FALSE;
         CLASS      ClassList[2];
         PQDESK_PARM qd;

GEQueryDesktopData *somThis = GEQueryDesktopGetData(somSelf);
GEQueryDesktopMethodDebug("GEQueryDesktop","qt_wpSetup");

cbBuffer = sizeof(szValue);

if (_wpScanSetupString(somSelf, pszSetupString,
                       "SHAREMEM", szValue, &cbBuffer ))
   {
   if (!DosGetNamedSharedMem((PVOID *) &pszRealName, szValue, PAG_WRITE))
      {
      qd = (PQDESK_PARM)pszRealName;
      strcpy(ObjectID, qd->String);
      qd->CallNr = 0;
      qd->String[0] = '\0';

      switch (qd->Action)
         {
         case ACTION_QUERY_FROM_OBJECTHANDLE:
              qd->somObject = _wpclsQueryObject(_WPObject, qd->ObjHandle);
              if (qd->somObject)
                 qd->CallNr++;
              else
                 Error = TRUE;
              break;
         case ACTION_QUERY_FROM_OBJECTID:
              qd->somObject = _wpclsQueryFolder(_WPObject, ObjectID, TRUE);
              if (qd->somObject)
                 {
                 qd->CallNr++;
                 qd->ObjHandle = _wpQueryHandle(qd->somObject);
                 }
              else
                 Error = TRUE;
              break;
         case ACTION_FIND_OBJECT_FIRST:
              ClassList[0] = NULL; /* _WPFileSystem; */
              ClassList[1] = NULL;
              qd->somDesktop = _wpclsQueryFolder(_WPObject, ObjectID, FALSE);
              if (!qd->somDesktop)
                 {
                 Error = TRUE;
                 break;
                 }
              qd->CallNr++;
              qd->FoundCt = 1;
              qd->FindObjectRC = _wpclsFindObjectFirst(_WPObject,
                                                       ClassList,
                                                       &qd->FindHandle,
                                                       "*",
                                                       qd->somDesktop,
                                                       TRUE,
                                                       NULL,
                                                       &qd->somObject,
                                                       &qd->FoundCt);
              if (!qd->FindObjectRC)
                 qd->ErrorCode = _wpclsQueryError(_WPObject);

              if (qd->FindObjectRC || (qd->ErrorCode == WPERR_BUFFER_OVERFLOW))
                 {
                 qd->CallNr++;
                 qd->ObjHandle = _wpQueryHandle(qd->somObject);
                 }
              else
                 Error = TRUE;
              break;
         case ACTION_FIND_OBJECT_NEXT:
              qd->FoundCt = 1;
              qd->FindObjectRC = _wpclsFindObjectNext(_WPObject,
                                                      qd->FindHandle,
                                                      &qd->somObject,
                                                      &qd->FoundCt);
              if (!qd->FindObjectRC)
                 qd->ErrorCode = _wpclsQueryError(_WPObject);

              if (qd->FindObjectRC || (qd->ErrorCode == WPERR_BUFFER_OVERFLOW))
                 {
                 qd->CallNr++;
                 qd->ObjHandle = _wpQueryHandle(qd->somObject);
                 }
              else
                 Error = TRUE;

              break;
         case ACTION_FIND_OBJECT_END:
              qd->FindObjectRC = _wpclsFindObjectEnd(_WPObject, qd->FindHandle);
              if (qd->FindObjectRC)
                 qd->CallNr++;
              Error = TRUE;   /* Just to skip the _wpQueryRealName function */
              break;
          } /* endswitch */

       if (!Error)
          {
          cb = CCHMAXPATH;
          if ((((ULONG)qd->ObjHandle) & 0xFFFF0000) == 0x00030000)
             {
             qd->QueryRNRC = (ULONG)_wpQueryRealName(qd->somObject, qd->String,
                                                     &cb, TRUE);
             if (qd->QueryRNRC)
                qd->CallNr++;
             }
          else
             {
             strcpy(qd->String, "(not a file system object)");
             qd->QueryRNRC = 1;
             qd->CallNr++;
             }
          }

       DosFreeMem(pszRealName);
       }
   }

    return (parent_wpSetup(somSelf,pszSetupString));
}

#undef SOM_CurrentClass
#define SOM_CurrentClass SOMMeta
SOM_Scope ULONG   SOMLINK qtM_wpclsQueryStyle(M_GEQueryDesktop *somSelf)
{
    /* M_GEQueryDesktopData *somThis = M_GEQueryDesktopGetData(somSelf); */
    M_GEQueryDesktopMethodDebug("M_GEQueryDesktop","qtM_wpclsQueryStyle");

    return (parent_wpclsQueryStyle(somSelf));
}
