//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ADMINWIN.RC
//
#define IDD_DIALOG2                     105
#define IDC_EDITBRANCH                  1005
#define IDSAVE                          1006
#define IDCREATE                        1008
#define IDDELETE                        1010
#define IDC_EDIT_ID                     1011
#define IDC_EDIT_PIN                    1013
#define IDC_COMBOBRANCH                 1015
#define IDC_CUSTOMERID                  1017
#define IDC_PIN                         1018
#define IDC_CUSTOMERNAME                1019
#define IDC_BRANCH                      1020
#define IDC_BALANCE                     1021
#define IDC_ACCOUNTTYPE                 1022
#define IDVIEW                          1023
#define IDCLOSE                         1024
#define IDSEARCH                        1025
#define IDM_ABOUT                       40001
#define IDM_EXIT                        40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
