#define ID_MAIN_WINDOW  10
#define ID_TIMER        20
#define ID_DLG_ABOUT    30
#define IC_SOM          40  

#define PB_KB_0         1000
#define PB_KB_1         1001
#define PB_KB_2         1002
#define PB_KB_3         1003
#define PB_KB_4         1004
#define PB_KB_5         1005
#define PB_KB_6         1006
#define PB_KB_7         1007
#define PB_KB_8         1008
#define PB_KB_9         1009
#define PB_KB_CANCEL    1010
#define PB_KB_CLR       1011
#define PB_KB_OK        1012
#define PB_KB_DOT       1013

#define GB_DISPLAY      2000
#define GB_KB           2001
#define GB_RESULT       2002
#define GB_ANIMATE      2003
#define RB_CHECKING     3000
#define RB_DEPOSIT      3001
#define RB_INQUIRE      3002
#define RB_SAVINGS      3003
#define RB_WITHDRAW     3004
#define STX_MSG_1       4000
#define STX_MSG_2       4001
#define STX_MSG_3       4002
#define STX_ENTRY       4003
#define STX_RESULT      4004
#define STX_SEL_1       4005
#define STX_SEL_2       4006
#define STX_SEL_3       4007

