
/*
 * This file was generated by the SOM Compiler.
 * FileName: recflder.h.
 * Generated using:
 *     SOM Precompiler spc: 1.21
 *     SOM Emitter emith: 1.11
 */

#ifndef recflder_h
#define recflder_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef RecordFolder
#define RecordFolder SOMAny
#endif
#include "wpfolder.h"

/*
 * Passthru lines: File: "C.h", "after"
 */

#define DebugBox(title, text)  WinMessageBox(HWND_DESKTOP,HWND_DESKTOP, \
                               (PSZ) text , (PSZ) title, 0, \
                               MB_OK | MB_INFORMATION )


#define RecordFolder_MajorVersion 1
#define RecordFolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define RecordFolderNewClass c
#pragma linkage(c, system)
#define RecordFolderClassData d
#define RecordFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define RecordFolder_classObj RecordFolderClassData.classObject
#define _RecordFolder RecordFolder_classObj

/*
 * New and Renew macros for RecordFolder
 */
#define _RecordFolderNew() (_somNew(RecordFolderClassData.classObject))
#define RecordFolderNew() \
	( RecordFolderClassData.classObject \
		? _RecordFolderNew() \
		: ( RecordFolderNewClass(RecordFolder_MajorVersion, RecordFolder_MinorVersion), _RecordFolderNew() ) )
#define RecordFolderRenew(buf) \
	( _somRenew(RecordFolderClassData.classObject, buf) )

/*
 * Override method: wpInitData
 */
#define RecordFolder_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpModifyPopupMenu
 */
#define RecordFolder_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define RecordFolder_wpMenuItemSelected(somSelf,hwndFrame,MenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,MenuId)

/*
 * Override method: wpSaveState
 */
#define RecordFolder_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define RecordFolder_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * New Method: UpdateLastQuery
 */
typedef BOOL    SOMLINK somTP_RecordFolder_UpdateLastQuery(RecordFolder *somSelf,
		PSZ szQuery);
#pragma linkage(somTP_RecordFolder_UpdateLastQuery, system)
typedef somTP_RecordFolder_UpdateLastQuery *somTD_RecordFolder_UpdateLastQuery;
#define somMD_RecordFolder_UpdateLastQuery "----"
#define RecordFolder_UpdateLastQuery(somSelf,szQuery) \
    (SOM_Resolve(somSelf, RecordFolder, UpdateLastQuery) \
	(somSelf,szQuery))
#define _UpdateLastQuery RecordFolder_UpdateLastQuery

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK RecordFolderNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(RecordFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct RecordFolderClassDataStructure {
	SOMAny *classObject;
	somMToken UpdateLastQuery;
} RecordFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct RecordFolderCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} RecordFolderCClassData;

#endif       /* recflder_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: recflder.h.
 * Generated using:
 *     SOM Precompiler spc: 1.21
 *     SOM Emitter emith: 1.11
 */

#ifndef recflder_mh
#define recflder_mh


/*
 * Define the class name as an object type
 */
#ifndef M_RecordFolder
#define M_RecordFolder SOMAny
#endif

#define M_RecordFolder_MajorVersion 1
#define M_RecordFolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_RecordFolderNewClass c
#pragma linkage(c, system)
#define M_RecordFolderClassData d
#define M_RecordFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_RecordFolder_classObj M_RecordFolderClassData.classObject
#define _M_RecordFolder M_RecordFolder_classObj

/*
 * New and Renew macros for M_RecordFolder
 */
#define _M_RecordFolderNew() (_somNew(M_RecordFolderClassData.classObject))
#define M_RecordFolderNew() \
	( M_RecordFolderClassData.classObject \
		? _M_RecordFolderNew() \
		: ( M_RecordFolderNewClass(M_RecordFolder_MajorVersion, M_RecordFolder_MinorVersion), _M_RecordFolderNew() ) )
#define M_RecordFolderRenew(buf) \
	( _somRenew(M_RecordFolderClassData.classObject, buf) )

/*
 * Override method: wpclsQueryTitle
 */
#define M_RecordFolder_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsInitData
 */
#define M_RecordFolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_RecordFolder_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_RecordFolderNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_RecordFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_RecordFolderClassDataStructure {
	SOMAny *classObject;
} M_RecordFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_RecordFolderCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_RecordFolderCClassData;

#endif       /* recflder_h */
