
# This file was generated by the SOM Compiler.
# FileName: recflder.psc.
# Generated using:
#     SOM Precompiler spc: 1.21
#     SOM Emitter emitpsc: 1.10

/*
 * Include the .sc file
 */
#include "recflder.sc"

class: RecordFolder;

