
/*
 * This file was generated by the SOM Compiler.
 * FileName: record.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef record_h
#define record_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef Record
#define Record SOMAny
#endif
#include "wptrans.h"

/*
 * Passthru lines: File: "C.h", "after"
 */

#define DebugBox(title, text)  WinMessageBox(HWND_DESKTOP,HWND_DESKTOP, \
                               (PSZ) text , (PSZ) title, 0, \
                               MB_OK | MB_INFORMATION )


#define Record_MajorVersion 1
#define Record_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define RecordNewClass c
#pragma linkage(c, system)
#define RecordClassData d
#define RecordCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define Record_classObj RecordClassData.classObject
#define _Record Record_classObj

/*
 * New and Renew macros for Record
 */
#define _RecordNew() (_somNew(RecordClassData.classObject))
#define RecordNew() \
	( RecordClassData.classObject \
		? _RecordNew() \
		: ( RecordNewClass(Record_MajorVersion, Record_MinorVersion), _RecordNew() ) )
#define RecordRenew(buf) \
	( _somRenew(RecordClassData.classObject, buf) )

/*
 * Override method: wpInitData
 */
#define Record_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define Record_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpModifyPopupMenu
 */
#define Record_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define Record_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define Record_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpSetup
 */
#define Record_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * New Method: SetRecordInfo
 */
typedef BOOL    SOMLINK somTP_Record_SetRecordInfo(Record *somSelf,
		PSZ szData);
#pragma linkage(somTP_Record_SetRecordInfo, system)
typedef somTP_Record_SetRecordInfo *somTD_Record_SetRecordInfo;
#define somMD_Record_SetRecordInfo "----"
#define Record_SetRecordInfo(somSelf,szData) \
    (SOM_Resolve(somSelf, Record, SetRecordInfo) \
	(somSelf,szData))
#define _SetRecordInfo Record_SetRecordInfo

/*
 * New Method: GetRecordInfo
 */
typedef BOOL    SOMLINK somTP_Record_GetRecordInfo(Record *somSelf,
		PSZ szData);
#pragma linkage(somTP_Record_GetRecordInfo, system)
typedef somTP_Record_GetRecordInfo *somTD_Record_GetRecordInfo;
#define somMD_Record_GetRecordInfo "----"
#define Record_GetRecordInfo(somSelf,szData) \
    (SOM_Resolve(somSelf, Record, GetRecordInfo) \
	(somSelf,szData))
#define _GetRecordInfo Record_GetRecordInfo

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK RecordNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(RecordNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct RecordClassDataStructure {
	SOMAny *classObject;
	somMToken SetRecordInfo;
	somMToken GetRecordInfo;
} RecordClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct RecordCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} RecordCClassData;

#endif       /* record_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: record.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef record_mh
#define record_mh


/*
 * Define the class name as an object type
 */
#ifndef M_Record
#define M_Record SOMAny
#endif

#define M_Record_MajorVersion 1
#define M_Record_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_RecordNewClass c
#pragma linkage(c, system)
#define M_RecordClassData d
#define M_RecordCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_Record_classObj M_RecordClassData.classObject
#define _M_Record M_Record_classObj

/*
 * New and Renew macros for M_Record
 */
#define _M_RecordNew() (_somNew(M_RecordClassData.classObject))
#define M_RecordNew() \
	( M_RecordClassData.classObject \
		? _M_RecordNew() \
		: ( M_RecordNewClass(M_Record_MajorVersion, M_Record_MinorVersion), _M_RecordNew() ) )
#define M_RecordRenew(buf) \
	( _somRenew(M_RecordClassData.classObject, buf) )

/*
 * Override method: wpclsInitData
 */
#define M_Record_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_Record_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_Record_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIcon
 */
#define M_Record_wpclsQueryIcon(somSelf) \
	M_WPObject_wpclsQueryIcon(somSelf)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_Record_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsFindObjectFirst
 */
#define M_Record_wpclsFindObjectFirst(somSelf,pClassList,phFind,pszTitle,Folder,fSubfolders,pExtendedCriteria,pBuffer,pCount) \
	M_WPObject_wpclsFindObjectFirst(somSelf,pClassList,phFind,pszTitle,Folder,fSubfolders,pExtendedCriteria,pBuffer,pCount)

/*
 * New Method: clsQueryDatabase
 */
typedef BOOL    SOMLINK somTP_M_Record_clsQueryDatabase(M_Record *somSelf,
		PSZ szSearch,
		WPObject *Folder);
#pragma linkage(somTP_M_Record_clsQueryDatabase, system)
typedef somTP_M_Record_clsQueryDatabase *somTD_M_Record_clsQueryDatabase;
#define somMD_M_Record_clsQueryDatabase "----"
#define M_Record_clsQueryDatabase(somSelf,szSearch,Folder) \
    (SOM_Resolve(somSelf, M_Record, clsQueryDatabase) \
	(somSelf,szSearch,Folder))
#define _clsQueryDatabase M_Record_clsQueryDatabase

/*
 * New Method: clsRestartServer
 */
typedef BOOL    SOMLINK somTP_M_Record_clsRestartServer(M_Record *somSelf);
#pragma linkage(somTP_M_Record_clsRestartServer, system)
typedef somTP_M_Record_clsRestartServer *somTD_M_Record_clsRestartServer;
#define somMD_M_Record_clsRestartServer "----"
#define M_Record_clsRestartServer(somSelf) \
    (SOM_Resolve(somSelf, M_Record, clsRestartServer) \
	(somSelf))
#define _clsRestartServer M_Record_clsRestartServer

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_RecordNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_RecordNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_RecordClassDataStructure {
	SOMAny *classObject;
	somMToken clsQueryDatabase;
	somMToken clsRestartServer;
} M_RecordClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_RecordCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_RecordCClassData;

#endif       /* record_h */
