/*************************************************************************/
/*                                                                       */
/* ITSC Redbook OS/2 v2.0 Sample Program                                 */
/*                                                                       */
/*                                                                       */
/* PWFinanceFile.C                                                       */
/*                                                                       */
/*                                                                       */
/*************************************************************************/

/*
 * This file was generated by the SOM Compiler.
 * FileName: pwFinanceFile.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */
#define INCL_WIN
#define INCL_DOS
#define INCL_GPIBITMAPS
#define INCL_WPCLASS
#define INCL_WPFOLDER
#define INCL_WINWORKPLACE
#define INCL_DOSERRORS

/******************************************************************************/
/* System-defined header files                                                */
/******************************************************************************/
#include <os2.h>

#include <pmwp.h>  /* eventually will be #define INCL_WINWORKPLACE */

#include <string.h>
#include <stdio.h>
#include <memory.h>
#include <stdlib.h>

/******************************************************************************/
/* Function prototype for dialog proc                                         */
/******************************************************************************/
MRESULT EXPENTRY PasswordDlgProc(HWND hwndDlg,
                                 ULONG msg,
                                 MPARAM mp1,
                                 MPARAM mp2);

/******************************************************************************/
/* Dialog definitions header file                                             */
/******************************************************************************/
#include "dialog.h"

/******************************************************************************/
/* Global data                                                                */
/******************************************************************************/
HPOINTER hLockedIcon;                            /* Handle for locked icon    */
HPOINTER hUnlockedIcon;                          /* Handle for unlocked icon  */

HMODULE  hmodThisClass;

PSZ      DefaultClassTitle = "Password FinanceFile";  /* Default FinanceFile title      */

CHAR       szFinanceFileWindowClass[] =    "Finance File Sample";
UCHAR      szFinanceFileClassTitle[CCHMAXPATH] = "";


#define PWFinanceFile_Class_Source
#include "pwFin.ih"

/******************************************************************************/
/* Non Method Function Prototypes                                             */
/******************************************************************************/
HWND PWFinanceFileInit (PWFinanceFile*);

MRESULT EXPENTRY FinanceFileWndProc ( HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2 );

#define OBJECT_FROM_DRAGITEM(di) (di&&di->ulItemID ? OBJECT_FROM_PREC(di->ulItemID) : NULL)

/*
 *
 *   METHOD:   QueryInfo                                   PRIVATE
 *
 *   PURPOSE:  Copies instance data into the PWF_INFO structure.
 *
 *   INVOKED:  From PasswordDlgProc
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_QueryInfo(PWFinanceFile *somSelf,
                PPWF_INFO pPWFinanceFileInfo)
{
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
           PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
          "pwFinanceFile_QueryInfo");

    strcpy(pPWFinanceFileInfo->szCurrentPassword,     /* Set user-entered password */
           _szCurrentPassword);
    strcpy(pPWFinanceFileInfo->szPassword,            /* Set FinanceFile password       */
           _szPassword);
    strcpy(pPWFinanceFileInfo->szUserid,              /* Set userid                */
           _szUserid);

    return (BOOL) 0;                             /* Return                    */
}

/*
 *
 *   METHOD:   SetInfo                                     PRIVATE
 *
 *   PURPOSE:  Sets instance data from the PWF_INFO structure.
 *
 *   INVOKED:  From PasswordDlgProc
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_SetInfo(PWFinanceFile *somSelf,
                PPWF_INFO pPWFinanceFileInfo)
{
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
           PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
          "pwFinanceFile_QueryInfo");

    strcpy(_szCurrentPassword,                   /* Save user-entered p'word  */
           pPWFinanceFileInfo->szCurrentPassword);
    strcpy(_szPassword,                          /* Save FinanceFile password      */
           pPWFinanceFileInfo->szPassword);
    strcpy(_szUserid,                            /* Save userid               */
           pPWFinanceFileInfo->szUserid);

    return (BOOL) 0;                             /* Return                    */
}

/*
 *
 *   METHOD:   LockFinanceFile                                  PUBLIC
 *
 *   PURPOSE:  Invalidates the current password, thereby locking the FinanceFile.
 *
 *   INVOKED:  From _wpMenuItemSelected
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_LockFinanceFile(PWFinanceFile *somSelf)
{
    BOOL bSuccess;

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
           PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
          "pwFinanceFile_QueryInfo");

    strcpy(_szCurrentPassword,"NOPASSWD");       /* Invalid user-entered      */
                                                 /* password                  */
    _wpSetTitle(somSelf,                         /* Set FinanceFile title to       */
                _wpQueryTitle(somSelf) );        /* locked state              */

    bSuccess=_wpSetIcon(somSelf,                 /* Set icon to locked state  */
                        hLockedIcon);

    _wpSaveImmediate(somSelf);                   /* Rember this state         */
    return (BOOL) 0;                             /* Return                    */
}

/*
 *
 *   METHOD:   wpInitData                                  PUBLIC
 *
 *   PURPOSE:  Initializes instance data
 *
 *   INVOKED:  By Workplace Shell, upon instantiation of the object instance.
 *
 */

SOM_Scope void   SOMLINK pwFinanceFile_wpInitData(PWFinanceFile *somSelf)
{
    CHAR  ErrorBuffer[100];

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpInitData");

/* set up the debug and tracing */
    SOM_TraceLevel=2;
    SOMOutCharRoutine = myReplacementForSOMOutChar;


    parent_wpInitData(somSelf);                  /* Invoke default processing */

    strcpy(_szCurrentPassword,"password");       /* Initialise FinanceFile in the  */
    strcpy(_szPassword,"password");              /* unlocked state            */
}

/*
 *
 *   METHOD:   wpModifyPopupMenu                           PUBLIC
 *
 *   PURPOSE:  Adds an additional "Lock" item to the object's context menu.
 *             Adds a "Open Finance File" item to the "Open" item
 *   INVOKED:  By Workplace Shell, upon instantiation of the object instance.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpModifyPopupMenu(PWFinanceFile *somSelf,
                HWND hwndMenu,
                HWND hwndCnr,
                ULONG iPosition)
{
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpModifyPopupMenu");

    _wpInsertPopupMenuItems(somSelf,             /* Insert menu item          */
                            hwndMenu,            /* Menu handle               */
                            iPosition,           /* Default position          */
                            hmodThisClass,       /* Module handle             */
                            ID_CXTMENU_LOCK,     /* Menu item identifier      */
                            0);                  /* No submenu identifier     */

    _wpInsertPopupMenuItems( somSelf,            /* Insert menu item          */
                             hwndMenu,           /* Menu handle               */
                             0,                  /* at the top!               */
                             hmodThisClass,      /* Module handle             */
                             ID_OPENFinanceFile, /* Menu item identifier      */
                             WPMENUID_OPEN);     /* Submenu identifier        */


    return(parent_wpModifyPopupMenu(somSelf,     /* Invoke default processing */
                                    hwndMenu,
                                    hwndCnr,
                                    iPosition));
}

/*
 *
 *   METHOD:   wpMenuItemSelected                          PUBLIC
 *
 *   PURPOSE:  Processes the user's selections from the context menu.  The
 *             overridden method processes the added "Lock" & "OPENFinanceFile"
 *             items, and passes all others to the parent method
 *
 *   INVOKED:  By Workplace Shell, upon selection of a menu item by the user.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpMenuItemSelected(PWFinanceFile *somSelf,
                HWND hwndFrame,
                ULONG ulMenuId)
{
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpMenuItemSelected");

    switch( ulMenuId )                           /* Switch on item identifier */
    {
       case IDM_LOCK:                            /* Lock item selected        */
          _LockFinanceFile(somSelf);                  /* Invoke _LockFinanceFile method */
          break;

    /*
     *   We could call wpOpen here, but, if the object is already opened,
     *   the following API determines whether the object should be
     *   resurfaced, or if multiple views are desired.
     *   Must call wpViewObject not wpOpen.  If you use wpOpen, multiple
     *   concurrent views won't work.  User can set object to open multiple views
     *   or switch to.  this function is free if you use wpViewObject.
     */

       case IDM_OPENFinanceFile:                 /* Open a view selected      */
          somPrintf("Open my finance file view\n");
          _wpViewObject(somSelf, NULLHANDLE, OPEN_FinanceFile, 0);
          somPrintf("After open my finance file view \n");
          break;


       default:                                  /* All other items           */
          parent_wpMenuItemSelected(somSelf,     /* Invoke default processing */
                                    hwndFrame,
                                    ulMenuId);
          break;
    }
}
/*
 *
 *   METHOD:   wpOpen                                      PUBLIC
 *
 *   PURPOSE:  Only allows a FinanceFile to be opened if the FinanceFile is unlocked, or
 *             if the user supplies the correct password in response to the
 *             dialog.
 *
 *   INVOKED:  By Workplace Shell, upon selection of the "Open" menu item by
 *             the user.
 *
 */

SOM_Scope HWND   SOMLINK pwFinanceFile_wpOpen(PWFinanceFile *somSelf,
                HWND hwndCnr,
                ULONG ulView,
                ULONG param)
{
    ULONG    ulResult;                           /* Return value              */
    CHAR     szTitle[100];                       /* FinanceFile title buffer       */
    PVOID    pCreateParam;
    BOOL     bAllowAccess = FALSE;               /* user is allowed in */

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpOpen");

    if ((strcmp(_szCurrentPassword,              /* If FinanceFile is locked   */
         _szPassword)) != 0)
    {
       somPrintf("ask for a password\n");
    pCreateParam = malloc( sizeof(ULONG) );      /* Allocate memory to pass a */
                                                 /* ULONG to the dialog proc  */
    *((PULONG)pCreateParam) = (ULONG)somSelf;    /* Put the somSelf pointer   */
                                                 /* in the CreateParam memory */

    ulResult = WinDlgBox(HWND_DESKTOP,           /* Display password dialog   */
                         HWND_DESKTOP,           /* Desktop is owner          */
                         PasswordDlgProc,        /* Dialog procedure address  */
                         hmodThisClass,          /* Module handle             */
                         ID_DLG_PASSWORD,        /* Dialog resource id        */
                         pCreateParam );         /* Create Param holding the  */
                                                 /* pointer to this object    */

    if (ulResult == DID_OK )                     /* If user hit OK button     */
       {
       if ((strcmp(_szCurrentPassword,           /* If password is correct    */
                   _szPassword)) == 0)
          {
          strcpy(szTitle,                        /* Get title string          */
                 _wpQueryTitle(somSelf));
          szTitle[strlen(szTitle)-9] = '\0';     /* Remove <LOCKED>           */
          _wpSetTitle(somSelf,szTitle);          /* Reset title string        */

          _wpSetIcon(somSelf,                    /* Set icon to unlocked      */
                     hUnlockedIcon);             /* state                     */

          /* now we can allow the user access to the object proper ! */
          bAllowAccess = TRUE;

          }
       else                                      /* Password is incorrect     */
          {
          WinMessageBox(HWND_DESKTOP,            /* Display message to user   */
                        HWND_DESKTOP,
                        "Password incorrect. FinanceFile remains locked.",
                        "Password Failed",
                        0,
                        MB_OK |
                        MB_CUAWARNING );
          return((HWND)0);                       /* Return NULL handle        */
          }
       }
    } else {
      bAllowAccess = TRUE;
    }
somPrintf("now test if allow access\n");
    if (bAllowAccess) {
       switch (ulView) {
       case OPEN_FinanceFile:
somPrintf("allow access...\n");
         if (!_wpSwitchTo(somSelf, ulView)) {
           /* Create a basic frame and client window for this instance */
           return PWFinanceFileInit(somSelf);
         } /* endif */
         break;

       default:
somPrintf("default processing\n");
         return(parent_wpOpen(somSelf,          /* Allow open to proceed in  */
                              hwndCnr,          /* normal way using default  */
                              ulView,           /* processing                */
                              param));
       } /* endswitch */
    } else {
somPrintf("not allowed access\n");
    } /* endif */
}


/*
 *
 *   METHOD:   wpSetTitle                                  PUBLIC
 *
 *   PURPOSE:  Sets the FinanceFile's title (icon text) to have the phrase <Locked>
 *             as a suffix if the FinanceFile is locked, or removes this suffix if
 *             the FinanceFile is unlocked.
 *
 *   INVOKED:  By wpOpen to set the unlocked state, and by LockFinanceFile to set
 *             the locked state.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpSetTitle(PWFinanceFile *somSelf,
                PSZ pszNewTitle)
{
    CHAR szBuf[100];                             /* Character buffer          */

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpSetTitle");

    strcpy(szBuf,pszNewTitle);                   /* Get current title         */

    if ((strcmp(_szCurrentPassword,              /* If FinanceFile is locked       */
                _szPassword)) != 0)
    {
       if ((strstr(szBuf,"LOCKED")) == NULL)     /* and <LOCKED> not in       */
       {                                         /* current title             */
          strcat(szBuf," <LOCKED>");             /* Add <LOCKED> to title     */
       }
    }
    return (parent_wpSetTitle(somSelf,szBuf));   /* Invoke default processing */
}

/*
 *
 *   METHOD:   wpSetup                                     PUBLIC
 *
 *   PURPOSE:  Sets FinanceFile properties based upon a setup string passed by the
 *             object's creator as part of the WinCreateObject() call.  The
 *             overridden method simply processes the PASSWORD keyword to set
 *             the FinanceFile's password immediately upon instantiation, before
 *             invoking the parent's default processing to handle all other
 *             keywords.
 *
 *   INVOKED:  By the Workplace Shell, upon instantiation of the object
 *             instance.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpSetup(PWFinanceFile *somSelf,
                PSZ pszSetupString)
{
    CHAR  pszInitPword[20];                      /* Character buffer          */
    BOOL  bFound;                                /* Success flag              */
    ULONG Length;                                /* Returned length           */

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Get debug info            */
                        "pwFinanceFile_wpSetup");

    if (*pszSetupString != '\0')                 /* If string is present      */
       {
       bFound=_wpScanSetupString(somSelf,        /* Parse setup string to     */
                                 pszSetupString, /* find PASSWORD keyword     */
                                 "PASSWORD",
                                 pszInitPword,   /* Buffer for keyword value  */
                                 &Length);       /* Length of returned string */

       if (bFound)
          {
          strcpy(_szPassword,                    /* Initialize FinanceFile         */
                 pszInitPword);                  /* password                  */
          strcpy(_szCurrentPassword,             /* Initialize user-entered   */
                 pszInitPword);                  /* password                  */
          }
       }
    return(parent_wpSetup(somSelf,               /* Invoke default processing */
                          pszSetupString));
}

/*
 *
 *   METHOD:   wpSaveState                                 PUBLIC
 *
 *   PURPOSE:  Saves the object instance's persistent state data.  The
 *             overridden method simply saves the password data, then invokes
 *             the parent's default processing to handle any other instance
 *             data defined by ancestor classes.
 *
 *   INVOKED:  By the Workplace Shell, when the object becomes dormant.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpSaveState(PWFinanceFile *somSelf)
{
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpSaveState");

    _wpSaveString(somSelf,                       /* Save FinanceFile password      */
                  "PWFinanceFile",                    /* Class name                */
                  1L,                            /* Class-defined key         */
                  _szPassword);                  /* String to be saved        */
    _wpSaveString(somSelf,                       /* Save user-entered p'word  */
                  "PWFinanceFile",                    /* Class name                */
                  2L,                            /* Class-defined key         */
                  _szCurrentPassword);           /* String to be saved        */

    return(parent_wpSaveState(somSelf));         /* Invoke default processing */
}

/*
 *
 *   METHOD:   wpRestoreState                              PUBLIC
 *
 *   PURPOSE:  Restores the object instance's persistent state data.  The
 *             overridden method simply restores the password data, then
 *             invokes the parent's default processing to handle any other
 *             instance data defined by ancestor classes.
 *
 *   INVOKED:  By the Workplace Shell, when the object becomes awake.
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpRestoreState(PWFinanceFile *somSelf,
                ULONG ulReserved)
{
    ULONG ulRetLength;                           /* Length of returned string */

    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile",              /* Set debug info            */
                        "pwFinanceFile_wpRestoreState");

    _wpRestoreString(somSelf,                    /* Restore FinanceFile password   */
                     "PWFinanceFile",                 /* Class name                */
                     1L,                         /* Class-defined key         */
                     _szPassword,                /* String to be restored     */
                     &ulRetLength);              /* Length of returned string */
    _wpRestoreString(somSelf,                    /* Restore user-entered pwd  */
                     "PWFinanceFile",                 /* Class name                */
                     2L,                         /* Class-defined key         */
                     _szCurrentPassword,         /* String to be restored     */
                     &ulRetLength);              /* Length of returned string */

    if ((strcmp(_szCurrentPassword,              /* If FinanceFile is locked       */
                _szPassword)) != 0)
    {
       _wpSetIcon(somSelf, hLockedIcon);         /* Set icon to locked state  */
    }

    return(parent_wpRestoreState(somSelf,        /* Invoke default processing */
                                 ulReserved));
}

/*
 *
 *   METHOD:   wpSetIcon                                   PUBLIC
 *
 *   PURPOSE:  This class method returns the handle to the correct icon for
 *             the object.
 *
 *   INVOKED:
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpSetIcon(PWFinanceFile *somSelf,
                HPOINTER hptrNewIcon)
{
    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpSetIcon");

    if ((strcmp(_szCurrentPassword,         /* If password is correct     */
                _szPassword)) == 0)
    {
       return (parent_wpSetIcon(somSelf,
                     hUnlockedIcon));       /* return pointer to unlocked */
    }
    else                                    /* otherwise                  */
    {
       return (parent_wpSetIcon(somSelf,
                     hLockedIcon));         /* return locked icon pointer */
    }
}

#undef SOM_CurrentClass
#define SOM_CurrentClass SOMMeta
/*
 *
 *   METHOD:   wpclsQueryTitle                             PUBLIC
 *
 *   PURPOSE:  This class method returns the default FinanceFile title for any
 *             instance of the password protected FinanceFile class.  This title
 *             is used if a title is not supplied in the WinCreateObject()
 *             call.
 *
 *   INVOKED:  By the Workplace Shell, upon instantiation of the object
 *             instance.
 *
 */

SOM_Scope PSZ   SOMLINK pwFinanceFilecls_wpclsQueryTitle(M_PWFinanceFile *somSelf)
{
    /* M_PWFinanceFileData *somThis = M_PWFinanceFileGetData(somSelf); */

    M_PWFinanceFileMethodDebug("M_PWFinanceFile",          /* Set debug info            */
                          "pwFinanceFilecls_wpclsQueryTitle");

    return(DefaultClassTitle);                   /* Return default title      */
}

/*
 *
 *   METHOD:   wpclsQueryIcon                              PUBLIC
 *
 *   PURPOSE:  This class method returns the handle to the default icon for
 *             the class.  This method is not used in the current version,
 *             but could be used if different icons are to be used for the
 *             locked and unlocked states.
 *
 *   INVOKED:
 *
 */

SOM_Scope HPOINTER   SOMLINK pwFinanceFilecls_wpclsQueryIcon(M_PWFinanceFile *somSelf)
{
    /* M_PWFinanceFileData *somThis = M_PWFinanceFileGetData(somSelf); */
    PWFinanceFileData *somThis =                      /* Get instance data pointer */
                 PWFinanceFileGetData(somSelf);

    M_PWFinanceFileMethodDebug("M_PWFinanceFile",          /* Set debug info            */
                          "pwFinanceFilecls_wpclsQueryIcon");

    return(hUnlockedIcon);
}

/*
 *
 *   METHOD:   wpclsInitData                               PUBLIC
 *
 *   PURPOSE:  This class method allows the initialization of any class data
 *             items.  The overridden method simply obtains a module handle
 *             to be used when accessing Presentation Manager resources, then
 *             invokes the parent's default processing.
 *
 *   INVOKED:  By the Workplace Shell, upon loading the class DLL.
 *
 */

SOM_Scope void   SOMLINK pwFinanceFilecls_wpclsInitData(M_PWFinanceFile *somSelf)
{
    APIRET apiret;

/*    M_PWFinanceFileData *somThis = M_PWFinanceFileGetData(somSelf); */

    M_PWFinanceFileMethodDebug("M_PWFinanceFile",          /* Set debug info            */
                          "pwFinanceFilecls_wpclsInitData");


    apiret = DosQueryModuleHandle("PWFin", & hmodThisClass);

    if (apiret == NO_ERROR)
       somPrintf("Handle OK\n");
    else
       {
       somPrintf("Handle Not OK tell me Why???\n");
       }

    hLockedIcon=WinLoadPointer(HWND_DESKTOP,     /* Load icons                */
                               hmodThisClass,
                               ID_LOCK);
    hUnlockedIcon=WinLoadPointer(HWND_DESKTOP,
                                 hmodThisClass,
                                 ID_UNLOCK);

    parent_wpclsInitData(somSelf);               /* Invoke default processing */
}

/*
 *
 *   METHOD:   wpclsUnInitData                             PUBLIC
 *
 *   PURPOSE:  This class method allows the release of any class data items
 *             or resources.  The overridden method releases the module handle
 *             obtained by wpclsInitData, then invokes the parent's default
 *             processing.
 *
 *   INVOKED:  By the Workplace Shell, upon unloading the class DLL.
 *
 */

SOM_Scope void   SOMLINK pwFinanceFilecls_wpclsUnInitData(M_PWFinanceFile *somSelf)
{
    /* M_PWFinanceFileData *somThis = M_PWFinanceFileGetData(somSelf); */

    M_PWFinanceFileMethodDebug("M_PWFinanceFile",          /* Set debug info            */
                          "pwFinanceFilecls_wpclsUnInitData");

    WinDestroyPointer(hLockedIcon);              /* Free icons                */
    WinDestroyPointer(hUnlockedIcon);

    parent_wpclsUnInitData(somSelf);
}

/******************************************************************************/
/*                                                                            */
/* PROCEDURE NAME:  PasswordDlgProc                                           */
/*                                                                            */
/* description:  Dialog procedure for password dialog                         */
/*                                                                            */
/* invoked:  By Presentation Manager, in response to FinanceFile issuing           */
/*           WinDlgBox() call from _wpOpen method.                            */
/*                                                                            */
/******************************************************************************/
MRESULT EXPENTRY PasswordDlgProc(HWND hwndDlg,
                                 ULONG msg,
                                 MPARAM mp1,
                                 MPARAM mp2)
{
   PWFinanceFile *aPWF;                               /* Define SOM pointer        */
   PWF_INFO pwFinanceFileInfo;                        /* Define password structure */
   CHAR     szTemp[100];                         /* Character buffer          */

   switch (msg)                                  /* Determine message class   */
   {
      case WM_INITDLG:                           /* Dialog being initialized  */

         WinSetWindowULong(hwndDlg,              /* Store SOM pointer in      */
                          QWL_USER,              /* window word QWL_USER      */
                          *((PULONG)mp2));
         free(mp2);                              /* Free Create Param memory  */
         break;

      case WM_COMMAND:                           /* User hit a pushbutton     */

         aPWF = (PWFinanceFile *)WinQueryWindowULong(hwndDlg, QWL_USER);

         _QueryInfo(aPWF,                        /* Get password data         */
                    &pwFinanceFileInfo);

         switch (SHORT1FROMMP(mp1))              /* Which button was hit?     */
         {
            case DID_OK:                         /* Okay button               */

               WinQueryDlgItemText(hwndDlg,      /* Get text from entryfield  */
                            ID_EF_PASSWORD,
                            sizeof(szTemp),
                            (PSZ)szTemp);

                                                 /* Copy to password data     */
               strcpy(pwFinanceFileInfo.szCurrentPassword, szTemp);

               _SetInfo(aPWF,&pwFinanceFileInfo);     /* Set instance data         */
               WinDismissDlg(hwndDlg,DID_OK);    /* Dismiss dialog            */
               break;

            case DID_CANCEL:                     /* Cancel button hit         */

               WinDismissDlg(hwndDlg,            /* Dismiss dialog            */
                             DID_CANCEL);
               break;
         }
         return(MRESULT)TRUE;                    /* Return from WM_COMMAND    */
         break;
   }
   return(WinDefDlgProc(hwndDlg,                 /* Invoke default PM message */
                        msg,                     /* handling                  */
                        mp1,
                        mp2));
}

/*
 *
 *   METHOD:   wpDraggedOverObject                         PUBLIC
 *
 *   PURPOSE:  Checks to see that the file is unlocked if user wants to
 *             drop the object on a program.
 *
 *   INVOKED:  By Workplace Shell, upon instantiation of the object instance.
 *
 */

//SOM_Scope MRESULT   SOMLINK pwFinanceFile_wpDraggedOverObject(PWFinanceFile *somSelf,
 MRESULT   SOMLINK pwFinanceFile_wpDraggedOverObject(PWFinanceFile *somSelf,
		WPObject *DraggedOverObject)
{
    CLASS          PWFinanceFileClass;

    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpDraggedOverObject");

    somPrintf("pwFinanceFile_wpDraggedOverObject");/* DHP */


    PWFinanceFileClass = _somClassFromId( SOMClassMgrObject,
                         SOM_IdFromString("PWFinanceFile") );

//    somPrintf(PWFinanceFileClass);

    if ((strcmp(_szCurrentPassword,              /* If FinanceFile is locked       */
                _szPassword)) != 0)
    {
        return (MRFROM2SHORT(DOR_NODROP,DO_UNKNOWN));
    }
    if (_somIsA(DraggedOverObject,_WPProgram)     ||
        _somIsA(DraggedOverObject, PWFinanceFileClass) ||
        _somIsA(DraggedOverObject,_WPProgramFile)) {

        return (MRFROM2SHORT(DOR_DROP,DO_MOVE));
      } /* endif */

    return (parent_wpDraggedOverObject(somSelf,DraggedOverObject));
}



/*
 *
 *   METHOD:   wpAddFileTypePage                           PUBLIC
 *
 *   PURPOSE:  This class method replaces the type page with the it's own one
 *             that only allows the FinanceFile Types.
 *
 *   INVOKED:  By the Workplace Shell, upon unloading the class DLL.
 *
 */

SOM_Scope ULONG   SOMLINK pwFinanceFile_wpAddFileTypePage(PWFinanceFile *somSelf,
		HWND hwndNotebook)
{
   PSZ psztype;
    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpAddFileTypePage");


// PAGEINFO pageinfo;
//
//    memset((PCH)&pageinfo,0,sizeof(PAGEINFO));
//    pageinfo.cb                 = sizeof(PAGEINFO);
//    pageinfo.hwndPage           = NULLHANDLE;
//    pageinfo.usPageStyleFlags   = BKA_MAJOR;
//    pageinfo.usPageInsertFlags  = BKA_FIRST;
//    pageinfo.pfnwp              = DashBoardDlgProc;
//    pageinfo.resid              = hmod;
//    pageinfo.dlgid              = IDD_PWFILETYPES;
//    pageinfo.pszName            = "File Type";
//    pageinfo.pCreateParams      = somSelf;
//    pageinfo.idDefaultHelpPanel = ID_HELP_DASHBOARD;
//    pageinfo.pszHelpLibraryName = szHelpLibrary;
//
//    return _wpInsertSettingsPage( somSelf, hwndNotebook, &pageinfo );

//  psztype = _wpQueryType(somSelf);
//  somPrintf("Data Type = >");
//  somPrintf(psztype);
//  somPrintf("<\n");
    return (SETTINGS_PAGE_REMOVED);
//    return (parent_wpAddFileTypePage(somSelf,hwndNotebook)); // do nothing

}

/*
 *
 *   METHOD:   wpDragOver                                  PUBLIC
 *
 *   PURPOSE:  Checks to see that the object being dragged over me is also
 *             either of my class or derived from me.
 *
 *   INVOKED:  By Workplace Shell, upon instantiation of the object instance.
 *
 */

SOMAny *queryObjectFromDragItem( PDRAGITEM pDragItem)
{
   WPObject *Object=NULL;

   if ( DrgVerifyRMF (pDragItem, "DRM_OBJECT", NULL)) {
     Object = OBJECT_FROM_DRAGITEM(pDragItem);
     somPrintf("OBJECT!!\n");
   } else {
         somPrintf("NOT AN OBJECT!!\n");
/* add code in here to deal with non-objects, eg datafiles, and lines */
/* selected from a listbox from a PWFinanceFile etc etc */
   } /* endif */
   return(Object);
}

SOM_Scope MRESULT   SOMLINK pwFinanceFile_wpDragOver(PWFinanceFile *somSelf,
		HWND hwndCnr,
		PDRAGINFO pdrgInfo)
{
    ULONG    ulItemCount         =0;
    ULONG    ulItem              =0;
    CLASS    PWFinanceFileClass;
    SOMAny  *ObjectBeingDragged;
    MRESULT  mr;
    USHORT   dropOperation,
             dropIndicator;

    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpDragOver");

    if ((strcmp(_szCurrentPassword,              /* If FinanceFile is locked       */
                _szPassword)) != 0)
    {
        return (MRFROM2SHORT(DOR_NODROP,DO_UNKNOWN));
    }

/* for each of the items being dragged, check to see that they are all */
/* derived from PWFinanceFileClass                                     */

    PWFinanceFileClass = _somClassFromId( SOMClassMgrObject,
                         SOM_IdFromString("PWFinanceFile") );

    /* firstly will all the source object(s) pass my parents tests? */
    mr = parent_wpDragOver(somSelf,hwndCnr,pdrgInfo);
    dropIndicator = SHORT1FROMMR(mr);
    dropOperation = SHORT2FROMMR(mr);

    if (dropIndicator != DOR_NEVERDROP)
    { somPrintf("passed parents testing\n");
      /* passed the parent's tests, so unless it fails this object's */
      /* tests we will allow the DROP                                */
      dropIndicator = DOR_DROP;
      dropOperation = DO_COPY;

      /* how many items are being dragged ? */
      ulItemCount = DrgQueryDragitemCount(pdrgInfo);

      /* search through the objects and abort if we find any that aren't derived */
      /* from PWFinanceFileClass                                                 */
  somPrintf("Number of Items being dragged = %i.\n",ulItemCount);
      for (ulItem=0; ulItem<ulItemCount; ulItem++) {
        PDRAGITEM pDragItem; /* temporary variable*/

        /* get one of the one or more drag items that we are receiving */
        pDragItem = DrgQueryDragitemPtr(pdrgInfo, ulItem);

        ObjectBeingDragged = queryObjectFromDragItem(pDragItem);

        if (ObjectBeingDragged) {
          if (!_somIsA(ObjectBeingDragged,PWFinanceFileClass)) {
somPrintf("Object %i, is rejected because it is not derived from PWFinanceFileClass\n",ulItem);
            return (MRFROM2SHORT(DOR_NEVERDROP,DO_UNKNOWN));
          } /* endif */
somPrintf("Object %i, is acceptable for dropping\n",ulItem);
        } else {
somPrintf("Object %i, is not a WPS object\n",ulItem);
//          return (MRFROM2SHORT(DOR_NEVERDROP,DO_UNKNOWN)); /* not an object */
        } /* endif */

      } /* for */
    } /* endif */
   return (MRFROM2SHORT(dropIndicator, dropOperation));

/* if we do the following line, the icon stays at the do not do symbol, why */
/* return (parent_wpDragOver(somSelf,hwndCnr,pdrgInfo)); */
}

/*
 *
 *   METHOD:   wpPrintObject                               PUBLIC
 *
 *   PURPOSE:  This class method allows this object to format it's output for
 *             printing.
 *
 *   INVOKED:
 *
 */

SOM_Scope BOOL   SOMLINK pwFinanceFile_wpPrintObject(PWFinanceFile *somSelf,
		PPRINTDEST pPrintDest,
		ULONG ulReserved)
{
   BOOL worked;

    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpPrintObject");
somPrintf("Yes this is the new PrintObject, printing is disabled\n");
      /* disable printing for now */
      return(FALSE);
//      return(parent_wpPrintObject(somSelf,pPrintDest,ulReserved));
}

/*
 *
 *   METHOD:   wpDrop                                      PUBLIC
 *
 *   PURPOSE:  To receive a dropped object.
 *
 *   INVOKED:  By Workplace Shell, when another object has been dropped on
 *             this object.
 *
 */

SOM_Scope MRESULT   SOMLINK pwFinanceFile_wpDrop(PWFinanceFile *somSelf,
		HWND hwndCnr,
		PDRAGINFO pdrgInfo,
		PDRAGITEM pdrgItem)
{

    CHAR          szName[CCHMAXPATH];
    CHAR          szPath[CCHMAXPATH];
    ULONG         cbPath = CCHMAXPATH;
    ULONG         ulItemCount         =0;
    ULONG         ulItem              =0;
    CLASS         PWFinanceFileClass;
    SOMAny       *ObjectBeingDragged;
    MRESULT       mr;
    USHORT        dropOperation,
                  dropIndicator;
    BOOL          flPrepared = TRUE; // Assume we do not need to do a prepare
    BOOL          flRendering = FALSE;
    PDRAGTRANSFER pDragTransfer;

    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpDrop");

    if ((strcmp(_szCurrentPassword,       /* If FinanceFile is NOT locked */
                _szPassword)) == 0)
    {

  /* make sure we are not dragging ourselves, and dropping onto ourselves */
     if (pdrgInfo->hwndSource != hwndCnr)
     {

     /* for each of the items being dropped, check to see that they are all */
     /* derived from PWFinanceFileClass                                     */

     PWFinanceFileClass = _somClassFromId( SOMClassMgrObject,
                          SOM_IdFromString("PWFinanceFile") );

      /* passed the parent's tests, so unless it fails this object's */
      /* tests we will allow the DROP                                */
      dropIndicator = DOR_DROP;
      dropOperation = DO_COPY;

      /* how many items are being dragged ? */
      ulItemCount = DrgQueryDragitemCount(pdrgInfo);

      /* search through the objects and abort if we find any that aren't derived */
      /* from PWFinanceFileClass                                                 */
      somPrintf("Number of Items being dropped = %i.\n",ulItemCount);
      for (ulItem=0; ulItem<ulItemCount; ulItem++) {
        PDRAGITEM pDragItem; /* temporary variable*/

        /* get one of the one or more drag items that we are receiving */
        pDragItem = DrgQueryDragitemPtr(pdrgInfo, ulItem);

        ObjectBeingDragged = queryObjectFromDragItem(pDragItem);

        if (ObjectBeingDragged) {
          if (!_somIsA(ObjectBeingDragged,PWFinanceFileClass)) {
            somPrintf("Object %i, is rejected for drop because it ",ulItem);
            somPrintf("is not derived from PWFinanceFileClass\n");
          } else {
            somPrintf("Object %i, is acceptable for dropping, by wpDROP\n",ulItem);
          } /* endif */
        } else {
          somPrintf("Object %i, is not a WPS object, can we render it\n",ulItem);

      /* start of code to render item */

      if( DrgVerifyRMF (pDragItem, "DRM_OS2FILE", NULL) )
      {
         somPrintf("An OS2FILE rendering method!\n");
         /* Protocol allows the source object to propose a target name...
          *
          * If it does, then try to use it, if it does not, then
          * try to use the source name, if present.  Finally, just
          * make up our own name...
          */
         if (pDragItem->hstrTargetName &&
             DrgQueryStrNameLen(pDragItem->hstrTargetName) )
         {
            DrgQueryStrName(pDragItem->hstrTargetName,
                            sizeof(szName),szName);
            somPrintf("Source proposes the target filename\n");
         }
         else
         {
            if (pDragItem->hstrSourceName &&
               DrgQueryStrNameLen(pDragItem->hstrSourceName))
            {
               DrgQueryStrName(pDragItem->hstrSourceName,
                               sizeof(szName),szName);
            somPrintf("Source proposes the source filename\n");

            }
            else
            {
               szName[0] = '\0';
               somPrintf("no source, nor target name\n");
            }
         }

         /* Allocate and initialize a drag transfer structure
          */
         somPrintf("allocating pDragtransfer structure\n");
         pDragTransfer = DrgAllocDragtransfer(1);

         if (pDragTransfer)
         {
            somPrintf("pDragtransfer structure allocated ok\n");
            /* create a file or directory now to get its true name
             */
            ObjectBeingDragged = _wpclsNew( _WPDataFile,
                                szName,
                                NULL,
                                _wpclsQueryFolder(_WPDataFile,"<WP_NOWHERE>",TRUE),
                                TRUE );

            if (ObjectBeingDragged)
            {
               somPrintf("ObjectBeingDragged has been successfully allocated\n");
               _wpQueryRealName(ObjectBeingDragged,szPath,&cbPath,TRUE);
               somPrintf("The ObjectBeingDragged filename is %s\n",szPath);

               /* fill in the struct now
                */
               pDragTransfer->cb               = sizeof(DRAGTRANSFER);
               pDragTransfer->hwndClient       = hwndCnr;
               pDragTransfer->pditem           = pDragItem;
               pDragTransfer->hstrSelectedRMF  =
                              DrgAddStrHandle("<DRM_OS2FILE,DRF_UNKNOWN>");
               pDragTransfer->hstrRenderToName = DrgAddStrHandle( szPath );
               pDragTransfer->ulTargetInfo     = 0L;
               pDragTransfer->usOperation      = pdrgInfo->usOperation;
               pDragTransfer->fsReply          = 0;


               /* Now, if the source wants prepared, do it...
                */
               if (pDragItem->fsControl & DC_PREPARE)
               {
                  somPrintf("Source wants prepared\n");
                  flPrepared = (BOOL)DrgSendTransferMsg(pdrgInfo->hwndSource,
                                                        DM_RENDERPREPARE,
                                                        (MPARAM)pDragTransfer,
                                                        (MPARAM)NULL);
               } else {
                  somPrintf("Source does not want prepared\n");
               }
               /* See if either we did not need to send a RENDERPREPARE, or
                * we have successfully done so...
                */
               if (flPrepared)
               {
                  somPrintf("not prepared\n");
                  /* Tell the source object where to put the file.
                   */
                  flRendering = (BOOL)DrgSendTransferMsg(pDragItem->hwndItem,
                                                         DM_RENDER,
                                                         (MPARAM)pDragTransfer,
                                                         (MPARAM)NULL);
                  if (!flRendering)
                  {
                     /* The partner object did not render, so delete
                      * the object we just created.
                      */
                     _wpFree(ObjectBeingDragged);
                     somPrintf("not rendering, we are deleting the object we just created\n");
                  } else {
                     somPrintf("rendering\n");
                  }
               }
               else
               {
                  somPrintf("Our partner wanted us to send him a prepare, and");
                  somPrintf("now has changed his mind about things..., ABORT\n");

                  /* Our partner wanted us to send him a prepare, and
                   * now has changed his mind about things...
                   * We cannot even send him an end conversation, as
                   * we do not know that the hwnd is any good.
                   *
                   * For now, we will treat this as an error.
                   */
                  mr = (MRESULT)RC_DROP_ERROR;
               }
            } else {
              somPrintf("ObjectBeingDragged has NOT been successfully allocated\n");
            }
            if (flRendering)
            {
               mr = RC_DROP_RENDERING;
            }
            else
            {
               DrgDeleteStrHandle( pDragTransfer->hstrRenderToName );
               DrgFreeDragtransfer( pDragTransfer );
            }
         }
      } else {
         somPrintf("Not an OS2FILE rendering methid\n");
      }


        } /* endif */

      } /* for */
    } else {
       somPrintf("we are trying to drop onto ourselves, not allowed\n");
    } /* endif */
  } else {
     somPrintf("LOCKED, drop is disallowed\n");
  } /* endif */

  return((MRESULT) NULL);

}

/*
 *
 *   METHOD:   wpFilterPopupMenu                           PUBLIC
 *
 *   PURPOSE:  This class method is called when the user asks for the context
 *             (popup) menu.
 *
 *   INVOKED:
 *
 */

SOM_Scope ULONG   SOMLINK pwFinanceFile_wpFilterPopupMenu(PWFinanceFile *somSelf,
		ULONG ulFlags,
		HWND hwndCnr,
		BOOL fMultiSelect)
{ ULONG ulPopupFlags;

    PWFinanceFileData *somThis = PWFinanceFileGetData(somSelf);
    PWFinanceFileMethodDebug("PWFinanceFile","pwFinanceFile_wpFilterPopupMenu");
    somPrintf("We were passed %o\n",ulFlags);

    /* first find out what our ancestors have done! */
//    ulPopupFlags = parent_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect);
//    somPrintf("Our ancestor changed this to %o\n",ulPopupFlags);
      ulPopupFlags = ulFlags;

    /* now what have the done to the "Create another" menu item */
    if ((ulPopupFlags & CTXT_NEW) == CTXT_NEW) {
       /* the "Create another" menu item is on our Popup, so remove it */
       somPrintf("'Create another' menu item is being removed\n");
       ulPopupFlags = ulPopupFlags & ~CTXT_NEW;
    } else {
       /* the "Create another" menu item is NOT on our Popup, so add it */
       somPrintf("'Create another' menu item is being added\n");
       ulPopupFlags = ulPopupFlags | CTXT_NEW;
    } /* endif */
    somPrintf("We changed this to %o\n",ulPopupFlags);

    return(ulPopupFlags);
}

/**************************  ORDINARY CODE SECTION  ***************************
*****                                                                     *****
*****                  Any non-method code should go here.                *****
*****                                                                     *****
******************************************************************************/
#undef SOM_CurrentClass


/***************************************************************************
*                                                                          *
*       ROUTINE:    PWFinanceFileInit()                                    *
*                                                                          *
*       DESCRIPTION:  PWFinanceFile Inisialisation                         *
*                                                                          *
*       RETURNS:    Handle of PWFinanceFile frame window, NULL if error    *
*                                                                          *
***************************************************************************/
HWND PWFinanceFileInit (PWFinanceFile* somSelf)
{

   HAB  hab;                                       /* PM anchor block handle */
   HWND hwndFrame = NULLHANDLE;                       /* Frame window handle */
   HWND hwndClient = NULLHANDLE;
   PWINDOWDATA pWindowData;
   BOOL fSuccess;
   SWCNTRL    swcEntry;                                      /* Switch Entry */
   FRAMECDATA flFrameCtlData;                              /* Frame Ctl Data */

   somPrintf("PWFinanceFileInit\n");

   hab = WinQueryAnchorBlock(HWND_DESKTOP);
   if (!WinRegisterClass( hab , szFinanceFileWindowClass, (PFNWP)FinanceFileWndProc ,
                            CS_SIZEREDRAW | CS_SYNCPAINT, sizeof(pWindowData)))
   {
      somPrintf("FinanceFileInit Failure in WinRegisterClass\n");
      return NULLHANDLE ;
   }

   /*
    *   Allocate some instance specific data in Window words of Frame window.
    *   This will ensure our window procedure can use this object's methods
    *   (our window proc isn't passed a * somSelf pointer).
    */
   pWindowData = (PWINDOWDATA) _wpAllocMem(somSelf, sizeof(*pWindowData), NULL);

   if (!pWindowData)
   {
      somPrintf("FinanceFileInit wpAllocMem failed to allocate pWindowData\n");
      return NULLHANDLE;
   }

   memset((PVOID) pWindowData, 0, sizeof(*pWindowData));
   pWindowData->cb = sizeof(*pWindowData);             /* first field = size */
   pWindowData->somSelf = somSelf;

   /* Create a frame window
    */
   flFrameCtlData.cb            = sizeof( flFrameCtlData );
   flFrameCtlData.flCreateFlags = FCF_SIZEBORDER | FCF_TITLEBAR | FCF_SYSMENU |
                                  FCF_MINMAX ;
   flFrameCtlData.hmodResources = hmodThisClass;
   flFrameCtlData.idResources   = ID_UNLOCK;

   hwndFrame =                                        /* create frame window */
   WinCreateWindow(
      HWND_DESKTOP,               /* parent-window handle                    */
      WC_FRAME,                   /* pointer to registered class name        */
      _wpQueryTitle(somSelf),     /* pointer to window text                  */
      0,                          /* window style                            */
      0, 0, 0, 0,                 /* position of window                      */
      NULLHANDLE,                 /* owner-window handle                     */
      HWND_TOP,                   /* handle to sibling window                */
      (USHORT) ID_FRAME,          /* window identifier                       */
      (PVOID) &flFrameCtlData,    /* pointer to buffer                       */
      NULL);      ;               /* pointer to structure with pres. params. */

   if (!hwndFrame)
   {
      somPrintf("FinanceFileInit Failure in WinCreateWindow\n");
      return NULLHANDLE;
   }
   hwndClient =         /* use WinCreateWindow so we can pass pres params */
   WinCreateWindow(
      hwndFrame,               /* parent-window handle                    */
      szFinanceFileWindowClass,        /* pointer to registered class name        */
      NULL,                    /* pointer to window text                  */
      0,                       /* window style                            */
      0, 0, 0, 0,              /* position of window                      */
      hwndFrame,               /* owner-window handle                     */
      HWND_TOP,                /* handle to sibling window                */
      (USHORT)FID_CLIENT,      /* window identifier                       */
      pWindowData,             /* pointer to buffer                       */
      NULL);                   /* pointer to structure with pres. params. */

   if (!hwndClient)
   {
      WinDestroyWindow(hwndFrame);
      return NULLHANDLE;
   }

   WinSendMsg(hwndFrame,WM_SETICON,MPFROMP(_wpQueryIcon(somSelf)),NULL);
   WinSetWindowText(WinWindowFromID(hwndFrame,(USHORT)FID_TITLEBAR),
                                                         _wpQueryTitle(somSelf));

   /*
    * Restore the Window Position
    */
   fSuccess =
   WinRestoreWindowPos(
      szFinanceFileClassTitle,                                        /* class title */
      _wpQueryTitle(somSelf),                                /* object title */
      hwndFrame);

   if (!fSuccess)
   {
    SWP        swp;

      /* Get the dimensions and the shell's suggested
       * location for the window
       */
      WinQueryTaskSizePos(hab,0,&swp);

      /* Set the frame window position
       */
      swp.fl               = SWP_SIZE|SWP_MOVE|SWP_RESTORE|SWP_ZORDER;
      WinSetWindowPos(hwndFrame, HWND_TOP, swp.x, swp.y, swp.cx,
                     swp.cy, swp.fl);
   }

   WinShowWindow(hwndFrame,TRUE);

   return hwndFrame;                                              /* success */

}   /* end FinanceFileInit() */


/******************************************************************************
*
*   FinanceFileWndProc()
*
*   DESCRIPTION: FinanceFile Window Procedure
*
******************************************************************************/
MRESULT EXPENTRY FinanceFileWndProc( HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2 )
{
  ULONG         MenuId;
  PWINDOWDATA   pWindowData;
  HWND          hwndFrame;
  CHAR          acBuffer[10];
  BOOL          fSuccess;
  CHAR          szPath[CCHMAXPATH];
  ULONG         cbPath = CCHMAXPATH;


   hwndFrame = WinQueryWindow(hwnd, QW_PARENT);

   switch( msg )
   {
      case WM_CREATE:

        pWindowData = (PWINDOWDATA) mp1;

        if (pWindowData == NULL)
        {
           somPrintf("FinanceFileWndProc:WM_CREATE couldn't get window words");
           return FALSE;
        }
        /*
         *   Fill in the class view/usage details and window specific data
         *   for this instance.
         *   Must create useitem, add it to the object's use list and register
         *   the view
         */

        pWindowData->UseItem.type    = USAGE_OPENVIEW;
        pWindowData->ViewItem.view   = OPEN_FinanceFile;
        /*
         * Must be frame.  be careful because this procedure is for the client.
         * must get parent and pass that as ViewItem.handle.
         */
        pWindowData->ViewItem.handle = hwndFrame;
        pWindowData->x               = 10;
        pWindowData->y               = 10;
        pWindowData->xDir            = 0;
        pWindowData->yDir            = 0;

        /*
         *   Set window pointer with object pointer and instance view info.
         *   Then add view to the in-use list so wpSwitchTo works.
         */
        WinSetWindowPtr(hwnd, QWL_USER, pWindowData);
        /*
         * _wpAddToObjUseList will tell the shell to store the view in
         * the internal linked list for the object to enable wpSwitchTo and other
         * methods to find the view.  The shell will also subclass the view window
         * this gives you title bar context menu when you call wpRegisterView.
         * wpRegisterView also puts the view in the window list and sets up
         * the title bar like:  "Object Title - View Title"
         */

        _wpAddToObjUseList(pWindowData->somSelf,&pWindowData->UseItem);
        _wpRegisterView(pWindowData->somSelf, hwndFrame,
                                             _wpQueryTitle(pWindowData->somSelf));
        WinSetFocus( HWND_DESKTOP, hwndFrame);

        /* what is the filename of the file */
        if (_wpQueryRealName(pWindowData->somSelf,szPath,&cbPath,TRUE))
           {
              somPrintf("File name is %s, size %i \n",szPath, cbPath);
           } else {
              somPrintf("Failed to get filename\n");
           } /* endif */

        break;

      case WM_COMMAND:

        break;

      case WM_PAINT:
         pWindowData = (PWINDOWDATA) WinQueryWindowPtr(hwnd, QWL_USER);

         if (pWindowData == NULL)
         {
            somPrintf("FinanceFileWndProc:WM_PAINT couldn't get window words\n");
            return FALSE;
         }
         else
         {
          HPS    hps;
          RECTL  rectl;

           hps = WinBeginPaint( hwnd, (HPS)NULLHANDLE, &rectl);
           WinFillRect( hps, &rectl, SYSCLR_WINDOW);
           WinEndPaint( hps );
         }
         break;

      case WM_CLOSE:
         {
          HAB hab;

            hab = WinQueryAnchorBlock(HWND_DESKTOP);

            pWindowData = (PWINDOWDATA) WinQueryWindowPtr(hwnd, QWL_USER);

            if (pWindowData == NULL)
            {
               somPrintf("FinanceFileWndProc:WM_CLOSE couldn't get window words\n");
               return FALSE;
            }
            fSuccess =
            WinStoreWindowPos(szFinanceFileClassTitle,_wpQueryTitle(pWindowData->somSelf),
                                                                        hwndFrame);
            /*
             * Must remove from obj use list when window is closed.  (can be done
             * on WM_DESTROY instead)
             */
            _wpDeleteFromObjUseList(pWindowData->somSelf,&pWindowData->UseItem);
            _wpFreeMem(pWindowData->somSelf,(PBYTE)pWindowData);

            WinDestroyWindow ( hwndFrame ) ;
         }
         break;

      default:
         return WinDefWindowProc( hwnd, msg, mp1, mp2 );
   }
   return FALSE;

}   /* end FinanceFileWndProc() */

