
/*
 * This file was generated by the SOM Compiler.
 * FileName: pwfolder.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef pwfolder_h
#define pwfolder_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef PWFolder
#define PWFolder SOMAny
#endif
#include "wpfolder.h"

/*
 * Passthru lines: File: "C.h", "after"
 */

#define DebugBox(title, text)  WinMessageBox(HWND_DESKTOP,HWND_DESKTOP, \
                               (PSZ) text , (PSZ) title, 0, \
                               MB_OK | MB_INFORMATION )


#define PWFolder_MajorVersion 1
#define PWFolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define PWFolderNewClass c
#pragma linkage(c, system)
#define PWFolderClassData d
#define PWFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define PWFolder_classObj PWFolderClassData.classObject
#define _PWFolder PWFolder_classObj

/*
 * New and Renew macros for PWFolder
 */
#define _PWFolderNew() (_somNew(PWFolderClassData.classObject))
#define PWFolderNew() \
	( PWFolderClassData.classObject \
		? _PWFolderNew() \
		: ( PWFolderNewClass(PWFolder_MajorVersion, PWFolder_MinorVersion), _PWFolderNew() ) )
#define PWFolderRenew(buf) \
	( _somRenew(PWFolderClassData.classObject, buf) )

/*
 * Override method: wpInitData
 */
#define PWFolder_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpModifyPopupMenu
 */
#define PWFolder_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define PWFolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define PWFolder_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpSetTitle
 */
#define PWFolder_wpSetTitle(somSelf,pszNewTitle) \
	WPObject_wpSetTitle(somSelf,pszNewTitle)

/*
 * Override method: wpSetup
 */
#define PWFolder_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpSaveState
 */
#define PWFolder_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define PWFolder_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSetIcon
 */
#define PWFolder_wpSetIcon(somSelf,hptrNewIcon) \
	WPObject_wpSetIcon(somSelf,hptrNewIcon)

/*
 * New Method: LockFolder
 */
typedef BOOL    SOMLINK somTP_PWFolder_LockFolder(PWFolder *somSelf);
#pragma linkage(somTP_PWFolder_LockFolder, system)
typedef somTP_PWFolder_LockFolder *somTD_PWFolder_LockFolder;
#define somMD_PWFolder_LockFolder "----"
#define PWFolder_LockFolder(somSelf) \
    (SOM_Resolve(somSelf, PWFolder, LockFolder) \
	(somSelf))
#define _LockFolder PWFolder_LockFolder

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK PWFolderNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(PWFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct PWFolderClassDataStructure {
	SOMAny *classObject;
	somMToken LockFolder;
	somMToken QueryInfo;
	somMToken SetInfo;
} PWFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct PWFolderCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} PWFolderCClassData;

#endif       /* pwfolder_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: pwfolder.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef pwfolder_mh
#define pwfolder_mh


/*
 * Define the class name as an object type
 */
#ifndef M_PWFolder
#define M_PWFolder SOMAny
#endif

#define M_PWFolder_MajorVersion 1
#define M_PWFolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_PWFolderNewClass c
#pragma linkage(c, system)
#define M_PWFolderClassData d
#define M_PWFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_PWFolder_classObj M_PWFolderClassData.classObject
#define _M_PWFolder M_PWFolder_classObj

/*
 * New and Renew macros for M_PWFolder
 */
#define _M_PWFolderNew() (_somNew(M_PWFolderClassData.classObject))
#define M_PWFolderNew() \
	( M_PWFolderClassData.classObject \
		? _M_PWFolderNew() \
		: ( M_PWFolderNewClass(M_PWFolder_MajorVersion, M_PWFolder_MinorVersion), _M_PWFolderNew() ) )
#define M_PWFolderRenew(buf) \
	( _somRenew(M_PWFolderClassData.classObject, buf) )

/*
 * Override method: wpclsQueryTitle
 */
#define M_PWFolder_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsInitData
 */
#define M_PWFolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryIcon
 */
#define M_PWFolder_wpclsQueryIcon(somSelf) \
	M_WPObject_wpclsQueryIcon(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_PWFolder_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_PWFolderNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_PWFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_PWFolderClassDataStructure {
	SOMAny *classObject;
} M_PWFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_PWFolderCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_PWFolderCClassData;

#endif       /* pwfolder_h */
